//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MostrarHora.Hora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hora.RetornarHoraSoap")]
    public interface RetornarHoraSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        MostrarHora.Hora.HelloWorldResponse HelloWorld(MostrarHora.Hora.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<MostrarHora.Hora.HelloWorldResponse> HelloWorldAsync(MostrarHora.Hora.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HoraResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hora", ReplyAction="*")]
        MostrarHora.Hora.HoraResponse Hora(MostrarHora.Hora.HoraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hora", ReplyAction="*")]
        System.Threading.Tasks.Task<MostrarHora.Hora.HoraResponse> HoraAsync(MostrarHora.Hora.HoraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public MostrarHora.Hora.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(MostrarHora.Hora.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public MostrarHora.Hora.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(MostrarHora.Hora.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hora", Namespace="http://tempuri.org/", Order=0)]
        public MostrarHora.Hora.HoraRequestBody Body;
        
        public HoraRequest() {
        }
        
        public HoraRequest(MostrarHora.Hora.HoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HoraRequestBody {
        
        public HoraRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HoraResponse", Namespace="http://tempuri.org/", Order=0)]
        public MostrarHora.Hora.HoraResponseBody Body;
        
        public HoraResponse() {
        }
        
        public HoraResponse(MostrarHora.Hora.HoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HoraResult;
        
        public HoraResponseBody() {
        }
        
        public HoraResponseBody(string HoraResult) {
            this.HoraResult = HoraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RetornarHoraSoapChannel : MostrarHora.Hora.RetornarHoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetornarHoraSoapClient : System.ServiceModel.ClientBase<MostrarHora.Hora.RetornarHoraSoap>, MostrarHora.Hora.RetornarHoraSoap {
        
        public RetornarHoraSoapClient() {
        }
        
        public RetornarHoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetornarHoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetornarHoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetornarHoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MostrarHora.Hora.HelloWorldResponse MostrarHora.Hora.RetornarHoraSoap.HelloWorld(MostrarHora.Hora.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            MostrarHora.Hora.HelloWorldRequest inValue = new MostrarHora.Hora.HelloWorldRequest();
            inValue.Body = new MostrarHora.Hora.HelloWorldRequestBody();
            MostrarHora.Hora.HelloWorldResponse retVal = ((MostrarHora.Hora.RetornarHoraSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MostrarHora.Hora.HelloWorldResponse> MostrarHora.Hora.RetornarHoraSoap.HelloWorldAsync(MostrarHora.Hora.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<MostrarHora.Hora.HelloWorldResponse> HelloWorldAsync() {
            MostrarHora.Hora.HelloWorldRequest inValue = new MostrarHora.Hora.HelloWorldRequest();
            inValue.Body = new MostrarHora.Hora.HelloWorldRequestBody();
            return ((MostrarHora.Hora.RetornarHoraSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MostrarHora.Hora.HoraResponse MostrarHora.Hora.RetornarHoraSoap.Hora(MostrarHora.Hora.HoraRequest request) {
            return base.Channel.Hora(request);
        }
        
        public string Hora() {
            MostrarHora.Hora.HoraRequest inValue = new MostrarHora.Hora.HoraRequest();
            inValue.Body = new MostrarHora.Hora.HoraRequestBody();
            MostrarHora.Hora.HoraResponse retVal = ((MostrarHora.Hora.RetornarHoraSoap)(this)).Hora(inValue);
            return retVal.Body.HoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MostrarHora.Hora.HoraResponse> MostrarHora.Hora.RetornarHoraSoap.HoraAsync(MostrarHora.Hora.HoraRequest request) {
            return base.Channel.HoraAsync(request);
        }
        
        public System.Threading.Tasks.Task<MostrarHora.Hora.HoraResponse> HoraAsync() {
            MostrarHora.Hora.HoraRequest inValue = new MostrarHora.Hora.HoraRequest();
            inValue.Body = new MostrarHora.Hora.HoraRequestBody();
            return ((MostrarHora.Hora.RetornarHoraSoap)(this)).HoraAsync(inValue);
        }
    }
}
